server:
  port: 9090

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: portfolio-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/public/**

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all actuator endpoints
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always


